name: Cli Test Lint

on:
  push:
    paths:
      - ".github/workflows/test-lint.yml"
  pull_request:
    types:
      - opened

jobs:
  lib-test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install modules
        run: pnpm install --no-frozen-lockfile

      - name: Run linters
        run: pnpm lint
